apiVersion: v1
kind: ReplicationController
metadata:
   name: geolocation-rc
   labels:
      name: geolocation-rc
      app: geolocation
spec:
   replicas: 2
   template:
      metadata:
         labels:
            name: geolocation-api
      spec:
         containers:
            - name: geolocation-api
              image: omkarshetkar/geolocation:1.3
              ports:
                 - containerPort: 8080
                   name: http
                   protocol: TCP
                   