apiVersion: "v1"
kind: Pod
metadata:
  name: geolocation-api
  labels:
    name: geolocation-api
    app: geolocation
spec:
  containers:
    - name: geolocation-api
      image: omkarshetkar/geolocation:1.2
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
          
